---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: maroon-gpd-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - kvantum
    remove:
      packages:
        - bazaar
        - lutris
        - sunshine
  - type: script
    snippets:
      - |
        set -eoux pipefail
        rm -f /usr/bin/sunshine
        rm -rf /usr/share/sunshine
        rm -f /usr/libexec/sunshine-postinst 2>/dev/null || true
        rm -f /usr/lib/systemd/user/sunshine.service 2>/dev/null || true
        rm -f /usr/lib/systemd/system/sunshine.service 2>/dev/null || true
        rm -f /usr/share/applications/dev.lizardbyte.app.Sunshine.desktop
        rm -f /usr/share/applications/dev.lizardbyte.app.Sunshine.terminal.desktop


  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
